config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :employee
root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
 def show
    @employee = Employee.find(params[:id])
  end
def new
end
def create
 @employee = Employee.new(params[:employee])
  @employee.save
  redirect_to @employee
end
private
  def employee_params
    params.require(:employee).permit(:empname, :empid, :taskid)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
def index
    @employees = Employee.all
  end

 def show
    @employee = Employee.find(params[:id])
  end

 def new
  @employee = Employee.new
  end
  
  def edit
  @employee = Employee.find(params[:id])
end
   def create
   @employee = Employee.new(employee_params)
 
   # respond_to do |format|
      if @employee.save
	  redirect_to @employee
	 
      else
        render 'new'
      end
    end
  
  
  private
  def employee_params
    params.require(:employee).permit(:empname, :empid, :taskid)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employee/new.html.erb
<h1>New employee</h1>
<%= form_for :employee,  url: employee_path do |f| %>
  <p>
    <%= f.label :empname %><br>
    <%= f.text_field :empname %>
  </p>
 
  <p>
    <%= f.label :empid %><br>
    <%= f.text_area :empid %>
  </p>
  
   <p>
    <%= f.label :taskid %><br>
    <%= f.text_area :taskid %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/employee/show.html.erb
<p>
  <strong>empname:</strong>
  <%= @employee.empname %>
</p>
 
<p>
  <strong>empid:</strong>
  <%= @employee.empid %>
</p>
<p>
  <strong>taskid:</strong>
  <%= @employee.taskid %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resource</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Rails new appn!</h1>